### ISSUE TITLE
Fix Android bundling

### ISSUE THREAD

**Issue by subsoap** [subsoap/discordrich#2]
![problem](https://user-images.githubusercontent.com/409170/51574158-84c9f600-1e61-11e9-8b66-62a8dd6766cc.png)

**Comment by dapetcu21** [comment]
Oooookkkkk... I'll take a look tomorrow

**Comment by subsoap** [comment]
Get a chance to look at it?

**Comment by dapetcu21** [comment]
Sorry. Didn't get a chance last week. Fixed it now and made a release.

**Comment by subsoap** [comment]
Great!!
